#!/bin/bash
set -e

GITLAB_CI_RUNNER_VERSION=5.0.0

INSTALL_DIR="/home/gitlab_ci_runner/gitlab-ci-runner"
DATA_DIR="/home/gitlab_ci_runner/data"
SETUP_DIR="/app/setup"
GEM_CACHE_DIR="${SETUP_DIR}/cache"

# add git user
adduser --disabled-login --gecos 'GitLab CI Runner' gitlab_ci_runner

ln -s ${DATA_DIR}/.ssh /home/gitlab_ci_runner/.ssh

# shallow clone gitlab-ci-runner
sudo -u gitlab_ci_runner -H git clone -b v${GITLAB_CI_RUNNER_VERSION} --depth 1 \
  https://github.com/gitlabhq/gitlab-ci-runner.git ${INSTALL_DIR}

cd ${INSTALL_DIR}

# rebuild apt cache
apt-get update

# install build dependencies for gem installation
apt-get install -y gcc g++ patch make \
  libc6-dev ruby2.1-dev zlib1g-dev libyaml-dev libssl-dev \
  libgdbm-dev libreadline-dev libncurses5-dev libffi-dev \
  libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev

# install gems required by gitlab-ci-runner, use cache if available
if [ -d "${GEM_CACHE_DIR}" ]; then
  mkdir -p vendor && mv ${GEM_CACHE_DIR} vendor/
  chown -R gitlab_ci_runner:gitlab_ci_runner vendor/
fi
sudo -u gitlab_ci_runner -H bundle install --path vendor/bundle

# create tmp/pids directory
sudo -u gitlab_ci_runner -H mkdir -m 0755 -p tmp/pids

# create symlink to builds directory
rm -rf tmp/builds
ln -sf ${DATA_DIR}/builds tmp/builds

touch /var/log/gitlab_ci_runner.log
chown gitlab_ci_runner:gitlab_ci_runner /var/log/gitlab_ci_runner.log

cat > /etc/supervisor/conf.d/runner.conf <<EOF
[program:runner]
numprocs=1
process_name=%(program_name)s_%(process_num)02d
priority=20
directory=${INSTALL_DIR}
environment=HOME=/home/gitlab_ci_runner
command=/usr/local/bin/bundle exec ./bin/runner
user=gitlab_ci_runner
autostart=true
autorestart=true
stopsignal=USR2
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF

# purge build dependencies
apt-get purge -y --auto-remove gcc g++ patch make \
  libc6-dev ruby2.1-dev zlib1g-dev libyaml-dev libssl-dev \
  libgdbm-dev libreadline-dev libncurses5-dev libffi-dev \
  libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev

# cleanup
rm -rf /var/lib/apt/lists/*

# make sure everything in /home/gitlab_ci_runner is owned by the gitlab_ci user
chown -R gitlab_ci_runner:gitlab_ci_runner /home/gitlab_ci_runner/

# install gitlab_ci_runner bootscript
cp lib/support/init.d/gitlab_ci_runner /etc/init.d/gitlab_ci_runner
chmod +x /etc/init.d/gitlab_ci_runner
