#!/bin/bash
set -e

INSTALL_DIR="/home/gitlab_ci_runner/gitlab-ci-runner"
DATA_DIR="/home/gitlab_ci_runner/data"

CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$DATA_DIR/certs/ca.crt}

# take ownership of /home/git/data
chown gitlab_ci_runner:gitlab_ci_runner ${DATA_DIR}

# create the .ssh directory
sudo -u gitlab_ci_runner -H mkdir -p ${DATA_DIR}/.ssh/
touch ${DATA_DIR}/.ssh/authorized_keys
chmod 700 ${DATA_DIR}/.ssh
chmod 600 ${DATA_DIR}/.ssh/authorized_keys
chown -R gitlab_ci_runner:gitlab_ci_runner ${DATA_DIR}/.ssh

cd ${INSTALL_DIR}

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" /usr/local/share/ca-certificates/ca.crt
  update-ca-certificates --fresh >/dev/null 2>&1
fi

appStart () {
  echo "Starting gitlab-ci-runner..."
  sudo -u gitlab_ci_runner -H ln -sf ${DATA_DIR}/config.yml config.yml
  exec bundle exec ./bin/runner
}

appSetup () {
  sudo -u gitlab_ci_runner -H bundle exec ./bin/setup
  sudo -u gitlab_ci_runner -H mv config.yml ${DATA_DIR}/config.yml
}

appHelp () {
  echo "Available options:"
  echo " app:start          - Starts the gitlab-ci server (default)"
  echo " app:setup          - Setup the runner."
  echo " app:help           - Displays the help"
  echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
  app:start)
    appStart
    ;;
  app:setup)
    appSetup
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
